version: "3"

services:
  pokemon:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    restart: always
    env_file:
      - .env
    networks:
      - mynetwork
networks:
  mynetwork:
    name: mynetwork
    driver: bridge